# Generated by Django 2.0.2 on 2018-02-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180209_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявлениея'},
        ),
    ]
