# Generated by Django 2.0.2 on 2018-02-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180209_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='desc',
            field=models.TextField(max_length=10000, verbose_name='Описание'),
        ),
    ]
